/**
 * Handler: wiki-reindex — regenerate the wiki table of contents.
 *
 * The *only* file this handler writes is ``<root>/.generated/INDEX.md``.
 * Authored pages are enumerated via listPages and grouped by kind.
 * Deterministic output: sorted by kind then path so unchanged wikis yield
 * byte-identical INDEX files.
 *
 * Phase 5 of ADR-2244: the INDEX gets two top-level sections —
 * ``Human-authored`` (the prior layout, by kind) followed by
 * ``Auto-generated reference`` (only present when auto-gen pages exist).
 * Both sections are still grouped by kind underneath.
 *
 * source: mcp_server/handlers/wiki_reindex.py
 */

import { PAGE_KINDS, indexPath } from "../layout.js";
import type { WikiKind } from "../types.js";
import { isRedirect, parseFrontmatter } from "../redirect.js";

const BANNER =
  "<!-- Generated by Cortex wiki-reindex — the authored pages are the source of truth. -->";

export interface WikiReindexResult {
  readonly path: string;
  readonly total_pages: number;
  readonly by_kind: Readonly<Record<string, number>>;
  readonly auto_generated_by_kind: Readonly<Record<string, number>>;
  readonly redirects_by_kind: Readonly<Record<string, number>>;
  readonly redirect_count: number;
  readonly auto_generated_count: number;
  readonly root: string;
}

export type WikiReindexResponse = WikiReindexResult | { readonly error: string };

export interface WikiReindexDeps {
  readonly wikiRoot: string;
  readonly listPages: (root: string, kind?: WikiKind | null) => Promise<string[]>;
  readonly readPage: (root: string, relPath: string) => Promise<string | null>;
  readonly writeFile: (absPath: string, content: string) => Promise<void>;
  readonly ensureDir: (absDir: string) => Promise<void>;
  readonly joinPath: (...parts: string[]) => string;
}

function renderSection(
  heading: string,
  grouped: Readonly<Record<string, string[]>>,
): string[] {
  const lines: string[] = [`## ${heading}`, ""];
  for (const kind of PAGE_KINDS) {
    const pages = grouped[kind] ?? [];
    lines.push(`### ${kind} (${pages.length})`);
    lines.push("");
    if (!pages.length) {
      lines.push("_No pages yet._");
      lines.push("");
      continue;
    }
    for (const rel of pages) {
      const name = rel.split("/").pop() ?? rel;
      lines.push(`- [${name}](../${rel})`);
    }
    lines.push("");
  }
  return lines;
}

function renderIndex(
  humanGrouped: Readonly<Record<string, string[]>>,
  autoGrouped: Readonly<Record<string, string[]>>,
): string {
  const humanTotal = Object.values(humanGrouped).reduce((s, ps) => s + ps.length, 0);
  const autoTotal = Object.values(autoGrouped).reduce((s, ps) => s + ps.length, 0);
  const total = humanTotal + autoTotal;

  const lines: string[] = [BANNER, "", "# Wiki Index", ""];
  lines.push(
    `**${total} authored pages across ${PAGE_KINDS.length} kinds.** ` +
      `${humanTotal} human-authored, ${autoTotal} auto-generated.`,
  );
  lines.push("");

  lines.push(...renderSection("Human-authored", humanGrouped));
  if (autoTotal > 0) {
    lines.push(...renderSection("Auto-generated reference", autoGrouped));
  }
  return lines.join("\n");
}

export async function handler(
  _args: Record<string, unknown>,
  deps: WikiReindexDeps,
): Promise<WikiReindexResponse> {
  // Three buckets per kind. Redirect stubs are navigational aids for
  // inbound links, not content to advertise — they are excluded from
  // both the rendered INDEX and the live/auto groupings, and counted
  // separately. source: cortex wiki_reindex.py:138-166 (handler) +
  // _classify_page:112-126.
  const humanGrouped: Record<string, string[]> = {};
  const autoGrouped: Record<string, string[]> = {};
  const redirectsByKind: Record<string, number> = {};
  const autoByKind: Record<string, number> = {};
  for (const kind of PAGE_KINDS) {
    humanGrouped[kind] = [];
    autoGrouped[kind] = [];
    redirectsByKind[kind] = 0;
    autoByKind[kind] = 0;
  }

  for (const kind of PAGE_KINDS) {
    let pages: string[] = [];
    try {
      pages = await deps.listPages(deps.wikiRoot, kind as WikiKind);
    } catch {
      pages = [];
    }
    for (const rel of pages) {
      let isRedirectStub = false;
      let isAuto = false;
      try {
        const content = await deps.readPage(deps.wikiRoot, rel);
        if (content !== null) {
          const fm = parseFrontmatter(content);
          isRedirectStub = isRedirect(fm);
          const prov = fm.provenance;
          isAuto =
            typeof prov === "string" &&
            prov.trim().toLowerCase() === "auto-generated";
        }
      } catch {
        isRedirectStub = false;
        isAuto = false;
      }
      // Redirects are skipped from both human and auto buckets.
      // source: cortex wiki_reindex.py:156-158
      if (isRedirectStub) {
        redirectsByKind[kind] = (redirectsByKind[kind] ?? 0) + 1;
        continue;
      }
      if (isAuto) {
        autoGrouped[kind]?.push(rel);
        autoByKind[kind] = (autoByKind[kind] ?? 0) + 1;
      } else {
        humanGrouped[kind]?.push(rel);
      }
    }
  }

  const content = renderIndex(humanGrouped, autoGrouped);
  const target = deps.joinPath(deps.wikiRoot, indexPath());
  const dir = target.split("/").slice(0, -1).join("/");

  try {
    await deps.ensureDir(dir);
    await deps.writeFile(target, content);
  } catch (err) {
    return { error: `reindex failed: ${String(err)}` };
  }

  // by_kind counts human-authored (live) pages only — excludes auto
  // and redirects. source: cortex wiki_reindex.py:179
  const byKind: Record<string, number> = {};
  for (const kind of PAGE_KINDS) {
    byKind[kind] = humanGrouped[kind]?.length ?? 0;
  }
  const humanCount = Object.values(byKind).reduce((s, n) => s + n, 0);
  const autoCount = Object.values(autoByKind).reduce((s, n) => s + n, 0);
  const redirectCount = Object.values(redirectsByKind).reduce((s, n) => s + n, 0);

  // total_pages excludes redirects (live + auto only).
  // source: cortex wiki_reindex.py:177-178
  return {
    path: indexPath(),
    total_pages: humanCount + autoCount,
    by_kind: byKind,
    auto_generated_by_kind: autoByKind,
    redirects_by_kind: redirectsByKind,
    redirect_count: redirectCount,
    auto_generated_count: autoCount,
    root: deps.wikiRoot,
  };
}

export const schema = {
  title: "Wiki — reindex",
  description:
    "Regenerate the wiki table of contents at <wiki_root>/.generated/INDEX.md " +
    "by enumerating every authored page and grouping it by kind. " +
    "Output has a Human-authored section followed by an Auto-generated " +
    "reference section (when auto-gen pages exist). Deterministic — " +
    "unchanged wikis yield byte-identical output.",
  inputSchema: {
    type: "object" as const,
    required: [] as const,
    properties: {} as const,
    additionalProperties: false,
  },
} as const;
