/**
 * Handler: wiki-list — enumerate authored wiki pages.
 *
 * Phase 3.2 of ADR-2244: redirect stubs are filtered from the listing by
 * default. Pass ``include_redirects: true`` to see them — useful for
 * migration tooling that needs to audit or clean up old paths.
 *
 * Phase 5 of ADR-2244: auto-generated pages (frontmatter ``provenance:
 * auto-generated``, written by ``codebase_analyze``) are also filtered
 * from the listing by default. At ~8,700 pages they dominate any listing
 * but they're lookup tables for code reference rather than curated
 * content; the default view should be human-authored content. Pass
 * ``include_auto_generated: true`` to see them.
 *
 * source: mcp_server/handlers/wiki_list.py
 */

import { PAGE_KINDS } from "../layout.js";
import type { WikiKind } from "../types.js";
import { isRedirect, parseFrontmatter } from "../redirect.js";

export interface WikiListArgs {
  readonly kind?: WikiKind | null;
  readonly include_redirects?: boolean;
  readonly include_auto_generated?: boolean;
}

export interface WikiListResult {
  readonly root: string;
  readonly count: number;
  readonly pages: readonly string[];
  readonly redirect_count: number;
  readonly auto_generated_count: number;
}

export type WikiListResponse = WikiListResult | { readonly error: string };

export interface WikiListDeps {
  readonly wikiRoot: string;
  readonly listPages: (root: string, kind?: WikiKind | null) => Promise<string[]>;
  readonly readPage: (root: string, relPath: string) => Promise<string | null>;
}

function classifyPage(content: string): { isRedirectStub: boolean; isAutoGenerated: boolean } {
  const fm = parseFrontmatter(content);
  const redirectFlag = isRedirect(fm);
  const rawProv = fm.provenance;
  const autoGenFlag =
    typeof rawProv === "string" && rawProv.trim().toLowerCase() === "auto-generated";
  return { isRedirectStub: redirectFlag, isAutoGenerated: autoGenFlag };
}

export async function handler(
  args: WikiListArgs,
  deps: WikiListDeps,
): Promise<WikiListResponse> {
  const kind = args.kind ?? null;
  const includeRedirects = Boolean(args.include_redirects ?? false);
  const includeAutoGenerated = Boolean(args.include_auto_generated ?? false);

  if (kind && !PAGE_KINDS.includes(kind)) {
    return { error: `unknown kind: ${kind}` };
  }
  let allPages: string[];
  try {
    allPages = await deps.listPages(deps.wikiRoot, kind);
  } catch (err) {
    return { error: `list failed: ${String(err)}` };
  }

  // Fast path when both filters are disabled.
  if (includeRedirects && includeAutoGenerated) {
    return {
      root: deps.wikiRoot,
      count: allPages.length,
      pages: allPages,
      redirect_count: 0,
      auto_generated_count: 0,
    };
  }

  const kept: string[] = [];
  let redirectCount = 0;
  let autoGeneratedCount = 0;

  for (const rel of allPages) {
    let content: string | null = null;
    try {
      content = await deps.readPage(deps.wikiRoot, rel);
    } catch {
      content = null;
    }
    if (content === null) {
      kept.push(rel);
      continue;
    }
    const { isRedirectStub, isAutoGenerated } = classifyPage(content);
    if (isRedirectStub) {
      redirectCount += 1;
      if (!includeRedirects) continue;
    }
    if (isAutoGenerated) {
      autoGeneratedCount += 1;
      if (!includeAutoGenerated) continue;
    }
    kept.push(rel);
  }

  return {
    root: deps.wikiRoot,
    count: kept.length,
    pages: kept,
    redirect_count: redirectCount,
    auto_generated_count: autoGeneratedCount,
  };
}

export const schema = {
  title: "Wiki — list pages",
  description:
    "Enumerate every authored wiki page under the wiki root. Optionally " +
    "restrict by kind (adr, tutorial, how-to, reference, explanation, " +
    "runbook, rfc, journal, plus legacy specs/guides/conventions/lessons/" +
    "notes/files). Two filters are applied by default and can be opted " +
    "out of: (1) redirect stubs are excluded — pass include_redirects: " +
    "true to see them; (2) auto-generated pages (provenance: auto-" +
    "generated, produced by codebase_analyze) are excluded — pass " +
    "include_auto_generated: true to see them. Returns {root, count, " +
    "pages, redirect_count, auto_generated_count}.",
  inputSchema: {
    type: "object" as const,
    required: [] as const,
    properties: {
      kind: {
        type: "string" as const,
        enum: [...PAGE_KINDS] as string[],
        description: "Restrict the listing to a single page kind.",
      },
      include_redirects: {
        type: "boolean" as const,
        default: false,
        description:
          "When true, redirect stubs are included in the listing. Default false.",
      },
      include_auto_generated: {
        type: "boolean" as const,
        default: false,
        description:
          "When true, auto-generated pages (provenance: auto-generated) are " +
          "included. Default false — at thousands of pages they dominate " +
          "listings.",
      },
    },
  },
} as const;
